### ISSUE TITLE
Logger sync between computers

### ISSUE THREAD

**Issue by mxxcon** [Finntaur/monkey#1]
It would be nice if logger script would somehow sync reviewed portals between computers.
Google drive sync the way iitc's unique portals plugin does it is a viable solution.
Or even if I could simply copy/paste reviewed portals from one computer to another, and it would somehow merge the results, that would work too.

**Comment by Finntaur** [comment]
You are completely right! That would be nice feature, but I decided to not implement it earlier since nobody in my community really expressed an actual need for it. However, I mashed up a quick'n'dirty copy-paste method for syncing/merging results between computers now that you brought it up. I might implement a more automatic and sensible syncing through Google drive at some point, when I get the chance to redesign this plugin. It's getting a bit too spaghetty-ish for my taste.
